### ISSUE TITLE
camera seems to be flipped

### ISSUE THREAD

**Issue by ianohare** [Scrawk/Proland-To-Unity#1]
If you use the transform.forward of a light as the sun direction, the light of the atmosphere appears to be coming from a different direction. It's not the exact opposite, inverting the sun direction won't fix it. It appears to be a problem with the camera view/projection.

**Comment by Scrawk** [comment]
The code for the matrix calculations was ported directly from the original Proland code due to the difficultly in getting this to work in Unity. Z is up in Proland and the view matrix includes this. The issue with the light being flipped is probably due to this.  

All the matrix math needs to be changed to use Unity's default matrices. I had planned that at some point but not sure if it will ever happen at the moment.
